### ISSUE TITLE
Crash at launch 

### ISSUE THREAD

**Issue by crest1993** [Globox1997/TooltipRareness#3]
MC 1.19 
TooltipRareness 1.0.5
Fabric API 0.56.0

https://pastebin.com/DjPu29nA

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/TooltipRareness/commit/ee06563fc2c81f73ba2d5dcad4ea6d765c3affb1](https://github.com/Globox1997/TooltipRareness/commit/ee06563fc2c81f73ba2d5dcad4ea6d765c3affb1)
